from moves.moves import BicepsLeft
from moves.moves import BicepsRight
from moves.moves import StretchedLeftArm
from moves.moves import StretchedRightArm
from moves.moves import RaisedLeftArm
from moves.moves import RaisedRightArm
from moves.moves import RestLeftArm
from moves.moves import RestRightArm
from moves.moves import HandTouch
from moves.moves import Raised
from moves.moves import Lowered
from moves.moves import StrongLeft
from moves.moves import StretchedLeftLeg
from moves.moves import StretchedRightLeg
from moves.moves import LeftHandMouth
from moves.moves import RightHandMouth
from moves.moves import Side
from moves.moves import Rest
from moves.moves import HeadToLeft
from moves.moves import HeadToRight
